### ISSUE TITLE
Change maven coordinates to be org.glassfish.concurro:concurro

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/glassfish-concurro#67]
We currently have `org.glassfish:jakarta.enterprise.concurrent` as maven coordinates. To be consistent with other projects I think this should become `org.glassfish.concurro:concurro`.

e.g.

* org.glassfish.hk2:hk2
* org.glassfish.exousia:exousia
* org.glassfish.wasp:wasp

Thoughts?

@OndroMih @aubi @avpinchuk @dmatej

**Comment by dmatej** [comment]
I agree. In the future there might be some submodules, so this is a good pattern.

**Comment by avpinchuk** [comment]
+1.

In my opinion, this looks reasonable.

**Comment by aubi** [comment]
I just added my last PR regarding virtual threads, so I don't have anything in progress. If nobody else has, it's good time to do this change.
Do you want to change package name as well?

**Comment by arjantijms** [comment]
> Do you want to change package name as well?

Yes, that should be a good change to do as well.
